name: new-workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: tibdex/github-app-token@v1
      id: get_installation_token
      with: 
        app_id: 170284
        private_key: ${{ secrets.PRIVATE_KEY }}

    - run: echo "Hello, world!"

    - run: exit 1

    - uses: LouisBrunner/checks-action@v1.3.1
      if: always()
      with:
        token: ${{ steps.get_installation_token.outputs.token }}
        name: Second Job
        conclusion: ${{ job.status }}
        # conclusion: action_required
        details_url: https://josh-ops.com/posts/github-code-coverage/
        action_url: https://josh-ops.com/posts/github-code-coverage/
        output: |
          {"summary":""}
        output_text_description_file: code-coverage-results.md

